export const galleryPageData = {
  bannerData: {
    title:
      'Explore our <span class = "italic text-secondary">Himalayan</span> Resort',
    description: ["A glimpse into luxury and experiences."],
    images: ["/images/gallery/banner.jpg"],
  },

  gallerySection: {
    title: "Stay above the clouds",
    link: {
      label: "Check Availability",
      href: "#",
    },

    galleryImages: [
      { src: "/picnic/Copy-of-Saraya-112-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-115-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-118-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-119-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-121-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-128-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-129-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-130-1.webp", alt: "picnic" },
      // { src: "/picnic/Copy-of-Saraya-134-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-135-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-150-1.webp", alt: "picnic" },
      { src: "/picnic/Copy-of-Saraya-69-1.webp", alt: "river side dine" },
      // { src: "/wine-&-dine/Copy-of-Saraya-133-1.webp", alt: "picnic" },
      { src: "/wine-&-dine/Copy-of-Saraya-136-1.webp", alt: "picnic" },
      { src: "/wine-&-dine/Copy-of-Saraya-137-1.webp", alt: "picnic" },
      // { src: "/wine-&-dine/Copy-of-Saraya-138-1.webp", alt: "picnic" },
      { src: "/wine-&-dine/Copy-of-Saraya-141-1.webp", alt: "picnic" },

      // { src: "/accommodation/Copy-of-Saraya-14-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-15-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-17-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-36-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-4-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-49-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-5-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-49-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-5-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-52-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-53-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-54-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-6-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-7-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-8-10.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-9-7.webp", alt: "accommodation" },




      { src: "/accommodation/Copy-of-Saraya-18-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-19-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-2-10.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-20-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-21-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-22-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-23-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-24-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-25-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-26-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-29-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-30-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-31-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-32-3.webp", alt: "accommodation" },

      // { src: "/accommodation/Copy-of-Saraya-42-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-48-1.webp", alt: "accommodation" },

      // { src: "/accommodation/Copy-of-Saraya-50-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-51-1.webp", alt: "accommodation" },

      // { src: "/accommodation/Copy-of-Saraya-53-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-54-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-55-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-56-1.webp", alt: "accommodation" },
      // { src: "/accommodation/Copy-of-Saraya-57-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-58-1.webp", alt: "accommodation" },
      
      { src: "/accommodation/Copy-of-Saraya-10-7.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-11-4.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-12-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-13-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-27-1.webp", alt: "accommodation" },
      { src: "/accommodation/Copy-of-Saraya-28-1.webp", alt: "accommodation" },

      { src: "/wine-&-dine/Copy-of-Saraya-143-1.webp", alt: "wine & dine" },
      { src: "/wine-&-dine/Copy-of-Saraya-148-1.webp", alt: "wine & dine" },
      { src: "/wine-&-dine/Copy-of-Saraya-39-1.webp", alt: "wine & dine" },
      // { src: "/wine-&-dine/Copy-of-Saraya-82-1.webp", alt: "wine & dine" },
      { src: "/wine-&-dine/Copy-of-Saraya-84-1.webp", alt: "wine & dine" },
      { src: "/wine-&-dine/1.jpg", alt: "wine & dine" },
      { src: "/wine-&-dine/2.jpg", alt: "wine & dine" },
      // { src: "/wine-&-dine/Copy-of-Saraya-85-1.webp", alt: "wine & dine" },
      // { src: "/wine-&-dine/Copy-of-Saraya-91-1.webp", alt: "wine & dine" },
      // { src: "/around-resort/Copy-of-Saraya-107-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-108-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-109-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-114-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-116-1.webp", alt: "picnic" },
      // { src: "/around-resort/Copy-of-Saraya-120-1.webp", alt: "picnic" },
      // { src: "/around-resort/Copy-of-Saraya-122-1.webp", alt: "picnic" },
      // { src: "/around-resort/Copy-of-Saraya-125-1.webp", alt: "picnic" },
      { src: "/around-resort/Copy-of-Saraya-322-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-33-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-34-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-35-1.webp", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-37-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-38-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-40-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-41-1.webp", alt: "around resort" },
      { src: "/around-resort/Copy-of-Saraya-43-1.webp", alt: "around resort" },
      { src: "/around-resort/resort1.jpg", alt: "around resort" },
      { src: "/around-resort/resort2.jpg", alt: "around resort" },
      { src: "/around-resort/resort3.jpg", alt: "around resort" },
      // { src: "/around-resort/resort4.jpg", alt: "around resort" },
      { src: "/around-resort/resort5.jpg", alt: "around resort" },
      { src: "/around-resort/resort6.jpg", alt: "around resort" },
      { src: "/around-resort/resort7.jpg", alt: "around resort" },
      { src: "/around-resort/resort8.jpg", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-44-1.webp", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-45-1.webp", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-46-1.webp", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-64-1.webp", alt: "river side dine" },
      // { src: "/around-resort/Copy-of-Saraya-66-1.webp", alt: "river side dine" },
      {
        src: "/around-resort/Copy-of-Saraya-67-1.webp",
        alt: "river side dine",
      },
      {
        src: "/around-resort/Copy-of-Saraya-68-1.webp",
        alt: "river side dine",
      },
      {
        src: "/around-resort/Copy-of-Saraya-72-1.webp",
        alt: "river side dine",
      },
      // { src: "/around-resort/Copy-of-Saraya-74-1.webp", alt: "river side dine" },
      {
        src: "/around-resort/Copy-of-Saraya-78-1.webp",
        alt: "river side dine",
      },
      {
        src: "/around-resort/Copy-of-Saraya-83-1.webp",
        alt: "river side dine",
      },
      {
        src: "/around-resort/Copy-of-Saraya-87-1.webp",
        alt: "river side dine",
      },
      // { src: "/around-resort/Copy-of-Saraya-88-1.webp", alt: "around resort" },
      // { src: "/around-resort/Copy-of-Saraya-89-1.webp", alt: "around resort" },
      {
        src: "/around-resort/Copy-of-Saraya-92-1.webp",
        alt: "river side dine",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-100-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-101-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-102-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-104-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-105-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-93-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-94-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-96-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-97-1.webp",
        alt: "cultural night",
      },
      {
        src: "/cultural-night/Copy-of-Saraya-99-1.webp",
        alt: "cultural night",
      },

      // { src: "/wine-&-dine/Copy-of-Saraya-82-1.webp", alt: "river side dine" },
      //  { src: "/wine-&-dine/Copy-of-Saraya-91-1.webp", alt: "river side dine" },
      { src: "/riversidedine/1.jpg", alt: "river side dine" },
      { src: "/riversidedine/2.jpg", alt: "river side dine" },
      { src: "/riversidedine/3.jpg", alt: "river side dine" },
      { src: "/riversidedine/4.jpg", alt: "river side dine" },
      { src: "/around-resort/Copy-of-Saraya-47-1.webp", alt: "wine & dine" },
      {
        src: "/around-resort/Copy-of-Saraya-59-1.webp",
        alt: "river side dine",
      },
      // { src: "/around-resort/Copy-of-Saraya-60-1.webp", alt: "river side dine" },
      // { src: "/around-resort/Copy-of-Saraya-62-1.webp", alt: "river side dine" },
    ],
  },
};
